version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "check-content"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gwfoe488eaa2"
s3_prefix = "check-content"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

